export const INTEGRATION_ENDPOINTS = {
  JELLYFIN: "/api/integrations/jellyfin",
  PROWLARR: "/api/integrations/prowlarr",
  PROWLARR_INDEXERS: "/api/integrations/prowlarr/indexers",
  JACKETT: "/api/integrations/jackett",
  JACKETT_INDEXERS: "/api/integrations/jackett/indexers",
  DOWNLOAD_CLIENT: "/api/integrations/download-client",
  DOWNLOAD_CLIENT_TEST: "/api/integrations/download-client/test",
  DOWNLOAD_CLIENT_HOOK: "/api/integrations/download-client/hook",
  DOWNLOAD_CLIENT_HOOK_ROTATE: "/api/integrations/download-client/hook/rotate",
  TMDB: "/api/integrations/tmdb",
  OIDC: "/api/integrations/oidc",
  LOCAL_AI: "/api/integrations/local-ai",
  LOCAL_AI_TEST: "/api/integrations/local-ai/test",
  GOOGLE_BOOKS: "/api/integrations/googlebooks",
  GOOGLE_BOOKS_TEST: "/api/integrations/googlebooks/test",
} as const;
